spring.application.name=Internship-Backend

# ✅ Railway port
server.port=${PORT:8080}

# ✅ Disable DB + JPA COMPLETELY
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration